Running on euler with following parameters : 
User : atabin
Model : unet
Data folder : /cluster/work/igp_psr/ai4good/group-1b/data/
Saving directory : /cluster/scratch/atabin/unet/
Checkpoint path : /cluster/scratch/atabin/checkpoints/unet/
  0%|          | 0/80 [00:00<?, ?it/s]{'model': 'unet', 'data_dir': '/cluster/work/igp_psr/ai4good/group-1b/data/', 'checkpoint_path': '/cluster/scratch/atabin/checkpoints/unet/', 'save_dir': '/cluster/scratch/atabin/unet/'}
Running unet...
train_path :  /cluster/work/igp_psr/ai4good/group-1b/data/train/
val_path :  /cluster/work/igp_psr/ai4good/group-1b/data/val/
inference_path :  /cluster/work/igp_psr/ai4good/group-1b/data/test/
Loading data...
Epoch 1:
  0%|          | 0/80 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/home/atabin/ClimateNet_AI4Good/run.py", line 33, in <module>
    train.run(
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/train.py", line 37, in run
    model.train(train)
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/models/unet/unet.py", line 64, in train
    outputs = torch.softmax(self.network(features), 1)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/models/unet/unet.py", line 234, in forward
    x3 = self.down2(x2)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/models/unet/unet.py", line 168, in forward
    x = self.down_conv(x)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 341, in conv2d_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 864.00 MiB (GPU 0; 10.76 GiB total capacity; 9.88 GiB already allocated; 100.69 MiB free; 9.90 GiB reserved in total by PyTorch)
Done!
