Running on euler with following parameters : 
User : atabin
Model : segnet
Data folder : /cluster/work/igp_psr/ai4good/group-1b/data/
Saving directory : /cluster/scratch/atabin/segnet/
Checkpoint path : /cluster/scratch/atabin/checkpoints/segnet/
{'model': 'segnet', 'data_dir': '/cluster/work/igp_psr/ai4good/group-1b/data/', 'checkpoint_path': '/cluster/scratch/atabin/checkpoints/segnet/', 'save_dir': '/cluster/scratch/atabin/segnet/'}
Running segnet...
Traceback (most recent call last):
  File "/cluster/home/atabin/ClimateNet_AI4Good/run.py", line 33, in <module>
    train.run(
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/train.py", line 14, in run
    model = Trainer(config, model_name)
  File "/cluster/home/atabin/ClimateNet_AI4Good/climatenet/models/trainer.py", line 71, in __init__
    self.network = MODELS[model_name](classes=len(self.config.labels), channels=len(list(self.config.fields))).cuda()
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 747, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
    module._apply(fn)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 662, in _apply
    param_applied = fn(param)
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 747, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/cluster/home/atabin/miniconda3/envs/climatenet/lib/python3.8/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Done!
